# Generated by Django 2.1 on 2018-08-07 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
